<?php

//
//Implement hook_help
//
function mytracer_help($path, $arg) {
  switch ($path) {
    case 'admin/help#mytracer':
      return '<p>' . t('mytracer模组在用户资料被浏览的情况时留下记录，提供这些记录在前台的显示，根据不同的设置执行不同的显示').
             '<p>' . t('前台的显示：1.用户主页mytracer页签下的表格显示  2.一个区块的显示').
             '<p>' . t('不同的设置："1.用户主页mytracer页签下的表格显示在"mytracer的管理基面进行设定，可设置显示多少笔记录；"2.一个区块的显示"在区块的管理界面上设置，可设置为合计或明细，明细为最新的10笔。');

    case 'admin/config/people/mytracer':
      return '<p>' . t('详细帮助信息请查看：').l(t('这里'), 'admin/help/mytracer');
  }
}


//
//Implement hook_menu
//
function mytracer_menu() {
  $items['admin/config/people/mytracer'] = array(
    'title' => t('mytracer管理界面'),
    'description'=>t('管理前台界面（用户菜单子页签）要秀出多少笔资料。'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mytracer_config_form'),
    'access arguments' => array('config mytracer'),
    'file'=>'mytracer.additional.inc',
  );
  $items['user/%user/mytracer'] = array(
    'title' => t('mytracer 追踪记录'),
    'description'=>t('列出用户资料笔浏览的情况。'),
    'page callback' => 'mytracer_records_table',
    'page arguments' => array(1),
    'access arguments' => array('view mytracer records'),
    'file'=>'mytracer.additional.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

//
//Implement hook_permission
//
function mytracer_permission() {
  return array(
    'config mytracer' => array(
      'title' => t('Config Mytracer'),
      'description' => t('管理mytracer'),
    ),
     'view mytracer records' => array(
      'title' => t('View Mytracer Records'),
      'description' => t('查看前台页签下用户资料被浏览记录的权限。'),
    ),
  );
}

//
//Implement hook_user_view
//

function mytracer_user_view($account, $view_mode, $langcode){
  global $user;
  if($view_mode<>'full') {return;}
  if($account->uid == $user->uid) {return;}
  //database table: uid_was_visited , uid_watched , visited_time , ip 
  db_insert('mytracer')
    ->fields(array(
    'uid_was_visited' => $account->uid, 
    'uid_watched' => $user->uid, 
    'visited_time' => REQUEST_TIME, 
    'ip' => ip_address(),
    ))
  ->execute();
}


//
//Implement hook_block_info
//
function mytracer_block_info() {
  $blocks['mytracer_block'] = array(
    'info' => t('摘要或明细'),
  );
  return $blocks;
}

//
//Implement hook_block_configure
//
function mytracer_block_configure($delta = '') {
  $form = array();
  if ($delta == 'mytracer_block') {
    $form['mytracer_block'] = array(
      '#type' => 'checkboxes',
      '#title' => t('选择列出摘要或者明细，默认为明细'),
      '#default_value' => variable_get('mytracer_block', array()),
      '#options' => array('nodetail'=>'nodetail'),
    );
  }
  return $form;
}

//
//Implement hook_block_save
//
function mytracer_block_save($delta = '', $edit = array()) {
  if ($delta == 'mytracer_block') {
    variable_set('mytracer_block', $edit['mytracer_block']);
  }
}


//
//Implement hook_block_view
//
function mytracer_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();
  variable_get('mytracer_block_limit', 10);
  global $user;
  $query = db_select('mytracer', 'mt')->condition('mt.uid_was_visited', $user->uid, '='); 
      $query->fields('mt', array('uid_watched', 'visited_time', 'ip'));
      $query->join('users', 'u', 'u.uid = mt.uid_watched');
      $query->fields('u',array('name'))->orderBy('visited_time', 'DESC');
      $result=$query->execute();
  if ($delta == 'mytracer_block'){
    $detailed=variable_get('mytracer_block', array());
    if($detailed['nodetail']){
      $items=array();
      foreach($result as $record){
        $account_obj=user_load($record->uid_watched);
        $username_link=theme('username',array('account'=>$account_obj));
        $items[]=array('data'=>$username_link);
      }
      $number=count($items);
      $block['content'] ='<p>'.t('总共有 @number 人访问过你的页面。',array('@number'=>$number)).'</p>';
    }
    else{
       $items=array();
       //$i=1;//只要最后的10个访客：第一种方法，用一个变数$i,
      foreach($result as $record){
        //if($i>10) break;
        $account_obj=user_load($record->uid_watched);
        $username_link=theme('username',array('account'=>$account_obj));
        $items[]=array('data'=>$username_link);
        //$i++;
      }
      //只要最后的10个访客：第2种方法，用array_splice();
      array_splice($items, 10);
      if(!$items){$block['content'] ='<p>'.t('还没有人看过你的页面哦。').'</p>';}
      else{
      $block['content'] =array(
        '#theme'=>'item_list',
        '#items'=>$items,
        '#type'=>'ol',
      );
      }
    }
      $block['subject'] = t('看过你页面的人');
      
  }
  return $block;
}